export const INDUSTRY_OPTIONS = [
  { value: "technology", label: "Technology" },
  { value: "software", label: "Software & SaaS" },
  { value: "healthcare", label: "Healthcare & Medical" },
  { value: "finance", label: "Finance & Banking" },
  { value: "insurance", label: "Insurance" },
  { value: "real_estate", label: "Real Estate" },
  { value: "construction", label: "Construction & Engineering" },
  { value: "manufacturing", label: "Manufacturing" },
  { value: "automotive", label: "Automotive" },
  { value: "transportation", label: "Transportation & Logistics" },
  { value: "retail", label: "Retail & E-commerce" },
  { value: "food_beverage", label: "Food & Beverage" },
  { value: "hospitality", label: "Hospitality & Tourism" },
  { value: "media", label: "Media & Entertainment" },
  { value: "telecommunications", label: "Telecommunications" },
  { value: "energy", label: "Energy & Utilities" },
  { value: "education", label: "Education & Training" },
  { value: "legal", label: "Legal & Law" },
  { value: "consulting", label: "Consulting" },
  { value: "marketing", label: "Marketing & Advertising" },
  { value: "nonprofit", label: "Nonprofit & NGO" },
  { value: "government", label: "Government & Public Sector" },
  { value: "pharmaceutical", label: "Pharmaceutical" },
  { value: "biotechnology", label: "Biotechnology" },
  { value: "aerospace", label: "Aerospace & Defense" },
  { value: "agriculture", label: "Agriculture & Farming" },
  { value: "other", label: "Other" },
];

export const COUNTRY_OPTIONS = [
  { value: "United States", label: "United States" },
  { value: "Canada", label: "Canada" },
  { value: "United Kingdom", label: "United Kingdom" },
  { value: "Germany", label: "Germany" },
  { value: "France", label: "France" },
  { value: "Italy", label: "Italy" },
  { value: "Spain", label: "Spain" },
  { value: "Netherlands", label: "Netherlands" },
  { value: "Belgium", label: "Belgium" },
  { value: "Switzerland", label: "Switzerland" },
  { value: "Sweden", label: "Sweden" },
  { value: "Norway", label: "Norway" },
  { value: "Denmark", label: "Denmark" },
  { value: "Finland", label: "Finland" },
  { value: "Ireland", label: "Ireland" },
  { value: "Austria", label: "Austria" },
  { value: "Portugal", label: "Portugal" },
  { value: "Poland", label: "Poland" },
  { value: "Czech Republic", label: "Czech Republic" },
  { value: "Australia", label: "Australia" },
  { value: "New Zealand", label: "New Zealand" },
  { value: "Singapore", label: "Singapore" },
  { value: "Japan", label: "Japan" },
  { value: "South Korea", label: "South Korea" },
  { value: "China", label: "China" },
  { value: "India", label: "India" },
  { value: "UAE", label: "United Arab Emirates" },
  { value: "Saudi Arabia", label: "Saudi Arabia" },
  { value: "Israel", label: "Israel" },
  { value: "Brazil", label: "Brazil" },
  { value: "Mexico", label: "Mexico" },
  { value: "Argentina", label: "Argentina" },
  { value: "Colombia", label: "Colombia" },
  { value: "Chile", label: "Chile" },
  { value: "South Africa", label: "South Africa" },
  { value: "Nigeria", label: "Nigeria" },
  { value: "Kenya", label: "Kenya" },
  { value: "Egypt", label: "Egypt" },
  { value: "Turkey", label: "Turkey" },
  { value: "Russia", label: "Russia" },
  { value: "Ukraine", label: "Ukraine" },
  { value: "Romania", label: "Romania" },
  { value: "Thailand", label: "Thailand" },
  { value: "Vietnam", label: "Vietnam" },
  { value: "Philippines", label: "Philippines" },
  { value: "Indonesia", label: "Indonesia" },
  { value: "Malaysia", label: "Malaysia" },
  { value: "Hong Kong", label: "Hong Kong" },
  { value: "Taiwan", label: "Taiwan" },
  { value: "Pakistan", label: "Pakistan" },
  { value: "Bangladesh", label: "Bangladesh" },
  { value: "Other", label: "Other" },
];

export const TIMEZONE_OPTIONS = [
  { value: "America/New_York", label: "Eastern Time (US & Canada) UTC-5" },
  { value: "America/Chicago", label: "Central Time (US & Canada) UTC-6" },
  { value: "America/Denver", label: "Mountain Time (US & Canada) UTC-7" },
  { value: "America/Los_Angeles", label: "Pacific Time (US & Canada) UTC-8" },
  { value: "America/Anchorage", label: "Alaska UTC-9" },
  { value: "Pacific/Honolulu", label: "Hawaii UTC-10" },
  { value: "America/Phoenix", label: "Arizona UTC-7" },
  { value: "America/Indiana/Indianapolis", label: "Indiana East UTC-5" },
  { value: "America/Toronto", label: "Eastern Time (Canada) UTC-5" },
  { value: "America/Vancouver", label: "Pacific Time (Canada) UTC-8" },
  { value: "America/Mexico_City", label: "Mexico City UTC-6" },
  { value: "America/Sao_Paulo", label: "Brasilia UTC-3" },
  { value: "America/Argentina/Buenos_Aires", label: "Argentina UTC-3" },
  { value: "America/Santiago", label: "Santiago UTC-3" },
  { value: "America/Bogota", label: "Bogota UTC-5" },
  { value: "Europe/London", label: "London (GMT/BST) UTC+0" },
  { value: "Europe/Paris", label: "Paris (CET/CEST) UTC+1" },
  { value: "Europe/Berlin", label: "Berlin (CET/CEST) UTC+1" },
  { value: "Europe/Madrid", label: "Madrid (CET/CEST) UTC+1" },
  { value: "Europe/Rome", label: "Rome (CET/CEST) UTC+1" },
  { value: "Europe/Amsterdam", label: "Amsterdam (CET/CEST) UTC+1" },
  { value: "Europe/Brussels", label: "Brussels (CET/CEST) UTC+1" },
  { value: "Europe/Zurich", label: "Zurich (CET/CEST) UTC+1" },
  { value: "Europe/Stockholm", label: "Stockholm (CET/CEST) UTC+1" },
  { value: "Europe/Oslo", label: "Oslo (CET/CEST) UTC+1" },
  { value: "Europe/Copenhagen", label: "Copenhagen (CET/CEST) UTC+1" },
  { value: "Europe/Dublin", label: "Dublin (GMT/IST) UTC+0" },
  { value: "Europe/Lisbon", label: "Lisbon (WET/WEST) UTC+0" },
  { value: "Europe/Warsaw", label: "Warsaw (CET/CEST) UTC+1" },
  { value: "Europe/Prague", label: "Prague (CET/CEST) UTC+1" },
  { value: "Europe/Istanbul", label: "Istanbul (TRT) UTC+3" },
  { value: "Europe/Moscow", label: "Moscow (MSK) UTC+3" },
  { value: "Europe/Kyiv", label: "Kyiv (EET/EEST) UTC+2" },
  { value: "Europe/Bucharest", label: "Bucharest (EET/EEST) UTC+2" },
  { value: "Europe/Athens", label: "Athens (EET/EEST) UTC+2" },
  { value: "Asia/Dubai", label: "Dubai (GST) UTC+4" },
  { value: "Asia/Riyadh", label: "Riyadh (AST) UTC+3" },
  { value: "Asia/Karachi", label: "Karachi (PKT) UTC+5" },
  { value: "Asia/Kolkata", label: "India (IST) UTC+5:30" },
  { value: "Asia/Dhaka", label: "Bangladesh (BST) UTC+6" },
  { value: "Asia/Bangkok", label: "Bangkok (ICT) UTC+7" },
  { value: "Asia/Singapore", label: "Singapore (SGT) UTC+8" },
  { value: "Asia/Hong_Kong", label: "Hong Kong (HKT) UTC+8" },
  { value: "Asia/Shanghai", label: "Beijing (CST) UTC+8" },
  { value: "Asia/Tokyo", label: "Tokyo (JST) UTC+9" },
  { value: "Asia/Seoul", label: "Seoul (KST) UTC+9" },
  { value: "Asia/Taipei", label: "Taipei (CST) UTC+8" },
  { value: "Asia/Jakarta", label: "Jakarta (WIB) UTC+7" },
  { value: "Asia/Manila", label: "Manila (PHT) UTC+8" },
  { value: "Asia/Ho_Chi_Minh", label: "Ho Chi Minh (ICT) UTC+7" },
  { value: "Asia/Tel_Aviv", label: "Tel Aviv (IST/IDT) UTC+2" },
  { value: "Australia/Sydney", label: "Sydney (AEST/AEDT) UTC+10" },
  { value: "Australia/Melbourne", label: "Melbourne (AEST/AEDT) UTC+10" },
  { value: "Australia/Brisbane", label: "Brisbane (AEST) UTC+10" },
  { value: "Australia/Perth", label: "Perth (AWST) UTC+8" },
  { value: "Pacific/Auckland", label: "Auckland (NZST/NZDT) UTC+12" },
  { value: "Africa/Cairo", label: "Cairo (EET) UTC+2" },
  { value: "Africa/Johannesburg", label: "Johannesburg (SAST) UTC+2" },
  { value: "Africa/Lagos", label: "Lagos (WAT) UTC+1" },
  { value: "Africa/Nairobi", label: "Nairobi (EAT) UTC+3" },
  { value: "Africa/Casablanca", label: "Casablanca (WET/WEST) UTC+0" },
];

const COUNTRY_TIMEZONE_MAP: Record<string, string[]> = {
  "United States": [
    "America/New_York", "America/Chicago", "America/Denver", "America/Los_Angeles",
    "America/Anchorage", "Pacific/Honolulu", "America/Phoenix", "America/Indiana/Indianapolis",
  ],
  "Canada": ["America/Toronto", "America/Vancouver"],
  "United Kingdom": ["Europe/London"],
  "Germany": ["Europe/Berlin"],
  "France": ["Europe/Paris"],
  "Italy": ["Europe/Rome"],
  "Spain": ["Europe/Madrid"],
  "Netherlands": ["Europe/Amsterdam"],
  "Belgium": ["Europe/Brussels"],
  "Switzerland": ["Europe/Zurich"],
  "Sweden": ["Europe/Stockholm"],
  "Norway": ["Europe/Oslo"],
  "Denmark": ["Europe/Copenhagen"],
  "Finland": ["Europe/Helsinki"],
  "Ireland": ["Europe/Dublin"],
  "Austria": ["Europe/Vienna"],
  "Portugal": ["Europe/Lisbon"],
  "Poland": ["Europe/Warsaw"],
  "Czech Republic": ["Europe/Prague"],
  "Australia": ["Australia/Sydney", "Australia/Melbourne", "Australia/Brisbane", "Australia/Perth"],
  "New Zealand": ["Pacific/Auckland"],
  "Singapore": ["Asia/Singapore"],
  "Japan": ["Asia/Tokyo"],
  "South Korea": ["Asia/Seoul"],
  "China": ["Asia/Shanghai"],
  "India": ["Asia/Kolkata"],
  "UAE": ["Asia/Dubai"],
  "Saudi Arabia": ["Asia/Riyadh"],
  "Israel": ["Asia/Tel_Aviv"],
  "Brazil": ["America/Sao_Paulo"],
  "Mexico": ["America/Mexico_City"],
  "Argentina": ["America/Argentina/Buenos_Aires"],
  "Colombia": ["America/Bogota"],
  "Chile": ["America/Santiago"],
  "South Africa": ["Africa/Johannesburg"],
  "Nigeria": ["Africa/Lagos"],
  "Kenya": ["Africa/Nairobi"],
  "Egypt": ["Africa/Cairo"],
  "Turkey": ["Europe/Istanbul"],
  "Russia": ["Europe/Moscow"],
  "Ukraine": ["Europe/Kyiv"],
  "Romania": ["Europe/Bucharest"],
  "Greece": ["Europe/Athens"],
  "Thailand": ["Asia/Bangkok"],
  "Vietnam": ["Asia/Ho_Chi_Minh"],
  "Philippines": ["Asia/Manila"],
  "Indonesia": ["Asia/Jakarta"],
  "Malaysia": ["Asia/Kuala_Lumpur"],
  "Hong Kong": ["Asia/Hong_Kong"],
  "Taiwan": ["Asia/Taipei"],
  "Pakistan": ["Asia/Karachi"],
  "Bangladesh": ["Asia/Dhaka"],
};

const TIMEZONE_LOOKUP: Record<string, string> = {};
for (const tz of TIMEZONE_OPTIONS) {
  TIMEZONE_LOOKUP[tz.value] = tz.label;
}

export function getFilteredTimezones(country?: string) {
  if (!country || !COUNTRY_TIMEZONE_MAP[country]) return TIMEZONE_OPTIONS;
  return COUNTRY_TIMEZONE_MAP[country].map((tz) => ({
    value: tz,
    label: TIMEZONE_LOOKUP[tz] || tz,
  }));
}
